### ISSUE TITLE
Question regarding the use of "predicate_closed=True" in the examples

### ISSUE THREAD

**Issue by liu-yang-maker** [linqs/psl-examples#19]
I have been reviewing the examples provided in the project and noticed that in all the examples, the predicate is consistently set as "predicate_closed=True". I would like to understand the rationale behind this choice and its implications for the project.

Could you example whether it should to distinguish the predicate as open or closed? Why the target predicate also set as "open"? Could you please provide some insights? Thanks a lot.

**Comment by eriq-augustine** [comment]
Hey,

When we are talking about open vs closed predicates, we are really talking about the types of variables (unobserved vs observed) that the predicate produces.

Closed predicates can only produce atoms that are observed.
Closed predicates have a [closed-world assumption](https://en.wikipedia.org/wiki/Closed-world_assumption) applied to them, so any ground atom that uses a closed predicate and does not have an explicitly defined value takes on a value of 0.0 (false).
These semantics are very similar to other SRL frameworks/languages (like MLNs) and other probabilistic programming in-general.

Open predicates **can have both** observed and unobserved values, and does not have the closed world assumption applied to them.
For open predicates, all reachable atoms (atoms that may be used in a ground rule) has to be specified.
To see a predicate that has both observed and unobserved data, you can look at the simple-acquaintances example.
You can see in the [data file for the most recent release](https://github.com/linqs/psl-examples/blob/2.3.2/simple-acquaintances/cli/simple-acquaintances.data#L2), that "Knows" is marked as open and has data loaded into both "observations" (observed data) and "targets" (unobserved data).
(Also note that the [new configuration format used in the next release](https://github.com/linqs/psl-examples/blob/main/simple-acquaintances/cli/simple-acquaintances.json#L21) does not explicitly state open/closed, but instead infers that information from the data provided.)

For reference, you can see the [canonical PSL paper](https://linqs.org/publications/#id:bach-jmlr17) (Section 4.1.2).

Hope this helps.

**Comment by liu-yang-maker** [comment]
Thanks for your reply!!!
